import { ChannelType, SlashCommandBuilder } from "discord.js";
import { BUILDINGS, MOBILIZATION_RULES, SHIPS, UNITS } from "../domain/catalog.js";
import { RESOURCE_CHOICES } from "../domain/resources.js";
import { BATTLE_TERRAINS, BATTLE_UNIT_STATS, NAVAL_UNIT_STATS, SIEGE_ASSET_BATTLE_STATS } from "../domain/battle.js";

const countryOption = (option: any) => option.setName("ulke").setDescription("Yalnızca DM: işlem yapılacak ülke").setRequired(false);

export const commandBuilders = [
  new SlashCommandBuilder()
    .setName("belge").setDescription("Ülkenin güncel belgesini gösterir")
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("alim").setDescription("Yerleşkede etkileşimli bina alımı başlatır")
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("asker-alimi").setDescription("Etkileşimli asker alımı başlatır")
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("asker-terhis").setDescription("Yerleşkedeki mevcut askerleri kalıcı olarak terhis eder")
    .addStringOption((option) => option.setName("yerleske").setDescription("Birliğin bulunduğu yerleşke").setRequired(true))
    .addStringOption((option) => option.setName("birim").setDescription("Terhis edilecek birlik türü").setRequired(true)
      .addChoices(...Object.entries(UNITS).map(([value, unit]) => ({ name: unit.name, value }))))
    .addStringOption((option) => option.setName("durum").setDescription("Birliğin mevcut konumu").setRequired(true)
      .addChoices({ name: "Garnizon", value: "GARRISON" }, { name: "Dost Bölgede Sefer", value: "FIELD_FRIENDLY" }, { name: "Düşman Bölgesinde Sefer", value: "FIELD_HOSTILE" }))
    .addIntegerOption((option) => option.setName("miktar").setDescription("Terhis edilecek asker sayısı").setMinValue(1).setRequired(true))
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("gemi-alimi").setDescription("Etkileşimli gemi alımı başlatır")
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("seferberlik").setDescription("Ülkenin seferberlik seviyesini değiştirir")
    .addStringOption((option) => option.setName("seviye").setDescription("Yeni seferberlik seviyesi").setRequired(true)
      .addChoices(...Object.entries(MOBILIZATION_RULES).map(([value, rule]) => ({ name: rule.label, value }))))
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("ticaret").setDescription("Ülkeler arası hammadde ticaretini yönetir")
    .addSubcommand((sub) => sub.setName("teklif").setDescription("Bir ülkenin yerleşkesine kaynak ticareti teklif eder")
      .addStringOption((o) => o.setName("hedef-ulke").setDescription("Teklif gönderilecek ülke").setRequired(true))
      .addStringOption((o) => o.setName("kendi-yerlesken").setDescription("Kaynak gönderecek yerleşkeniz").setRequired(true))
      .addStringOption((o) => o.setName("hedef-yerleske").setDescription("Karşı tarafın kaynak gönderecek yerleşkesi").setRequired(true))
      .addStringOption((o) => o.setName("tur").setDescription("Ticaret güzergâhı").setRequired(true).addChoices({ name: "Kara Ticareti", value: "LAND" }, { name: "Deniz Ticareti", value: "SEA" }))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("liste").setDescription("Bekleyen ve aktif kaynak ticaretlerini gösterir")
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("feshet").setDescription("Aktif antlaşmalar arasından feshedilecek olanı seçtirir")
      .addStringOption(countryOption)),
  new SlashCommandBuilder()
    .setName("tur").setDescription("Resmî tur durumunu yönetir ve herkese açık duyuru yayımlar")
    .addSubcommand((sub) => sub.setName("atla").setDescription("Sonraki tura geçer ve yeni turu açar"))
    .addSubcommand((sub) => sub.setName("ac").setDescription("Mevcut turu oyuncu hareketlerine açar"))
    .addSubcommand((sub) => sub.setName("durdur").setDescription("Oyuncu hareketlerini durdurup olay çözümüne geçer"))
    .addSubcommand((sub) => sub.setName("kapat").setDescription("Mevcut turu tamamen kapatır")),
  new SlashCommandBuilder()
    .setName("zar").setDescription("Zar atar")
    .addIntegerOption((option) => option.setName("adet").setDescription("Zar adedi").setMinValue(1).setMaxValue(20).setRequired(true))
    .addIntegerOption((option) => option.setName("yuz").setDescription("Zarın yüz sayısı").setMinValue(2).setMaxValue(10_000).setRequired(true))
    .addIntegerOption((option) => option.setName("bonus").setDescription("Sonuca eklenecek bonus").setMinValue(-10_000).setMaxValue(10_000))
    .addBooleanOption((option) => option.setName("gizli").setDescription("Sonucu yalnızca sen gör")),
  new SlashCommandBuilder()
    .setName("rol-siralama").setDescription("Rol kanallarındaki kelime sıralamasını gösterir")
    .addStringOption((option) => option.setName("donem").setDescription("Sıralama dönemi").setRequired(true)
      .addChoices({ name: "Son 24 saat", value: "daily" }, { name: "Son 7 gün", value: "weekly" })),
  new SlashCommandBuilder()
    .setName("savas").setDescription("Kalıcılığa sahip açık zar savaş sistemini yönetir")
    .addSubcommand((sub) => sub.setName("baslat").setDescription("Bu kanalda yeni savaş taslağı oluşturur")
      .addStringOption((o) => o.setName("taraf-a").setDescription("A tarafındaki ülke").setRequired(true))
      .addStringOption((o) => o.setName("taraf-b").setDescription("B tarafındaki ülke").setRequired(true))
      .addStringOption((o) => o.setName("arazi").setDescription("Savaş alanı hazır ayarı").setRequired(true).addChoices(...Object.entries(BATTLE_TERRAINS).map(([value, terrain]) => ({ name: terrain.label, value }))))
      .addStringOption((o) => o.setName("kontrol-a").setDescription("A tarafının zar yetkisi").setRequired(true).addChoices({ name: "Ülke Oyuncuları", value: "PLAYERS" }, { name: "Oyun Yöneticisi / NPC", value: "GM" }))
      .addStringOption((o) => o.setName("kontrol-b").setDescription("B tarafının zar yetkisi").setRequired(true).addChoices({ name: "Ülke Oyuncuları", value: "PLAYERS" }, { name: "Oyun Yöneticisi / NPC", value: "GM" }))
      .addStringOption((o) => o.setName("anlatim").setDescription("Herkese açık savaş açılış metni").setMaxLength(1000)))
    .addSubcommand((sub) => sub.setName("birlik-ayarla").setDescription("Taslağın gizli birlik kadrosuna bir birlik yazar")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addStringOption((o) => o.setName("birim").setDescription("Birim türü").setRequired(true).addChoices(...Object.entries(BATTLE_UNIT_STATS).map(([value, unit]) => ({ name: unit.label, value }))))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Bu türden asker sayısı; silmek için 0").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("kadro-ayarla").setDescription("Bir tarafın bütün kara ordusu kadrosunu tek komutla yazar")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addIntegerOption((o) => o.setName("hafif-piyade").setDescription("Hafif Piyade / Ciritçi").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("sapanci").setDescription("Sapancı").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("mizrakli").setDescription("Mızraklı Piyade").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("okcu").setDescription("Okçu").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("agir-piyade").setDescription("Ağır Piyade").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("hafif-suvari").setDescription("Hafif Süvari").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("agir-suvari").setDescription("Ağır Süvari").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("gemi-ayarla").setDescription("Deniz savaşı taslağının gizli gemi kadrosunu düzenler")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addStringOption((o) => o.setName("gemi").setDescription("Gemi türü").setRequired(true).addChoices(...Object.entries(NAVAL_UNIT_STATS).map(([value, unit]) => ({ name: unit.label, value }))))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Gemi sayısı; silmek için 0").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("filo-ayarla").setDescription("Bir tarafın bütün filosunu tek komutla yazar")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addIntegerOption((o) => o.setName("kerkouros").setDescription("Kerkouros sayısı").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("trireme").setDescription("Trireme sayısı").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("quinquereme").setDescription("Quinquereme sayısı").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("kusatma-aleti-ayarla").setDescription("Kuşatma taslağının gizli savaş aletlerini düzenler")
      .addStringOption((o) => o.setName("taraf").setDescription("A saldıran, B savunandır").setRequired(true).addChoices({ name: "A — Kuşatan", value: "A" }, { name: "B — Savunan", value: "B" }))
      .addStringOption((o) => o.setName("alet").setDescription("Kuşatma aleti").setRequired(true).addChoices(...Object.entries(SIEGE_ASSET_BATTLE_STATS).map(([value, asset]) => ({ name: asset.label, value }))))
      .addStringOption((o) => o.setName("hedef").setDescription("Aletin bu savaşta vuracağı hedef").setRequired(true).addChoices({ name: "Sur", value: "WALL" }, { name: "Kapı", value: "GATE" }, { name: "Düşman Ordusu", value: "ARMY" }, { name: "Hücum Desteği", value: "ASSAULT" }))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Alet sayısı; silmek için 0").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("yayinla").setDescription("Taslağı herkese açık savaş kartı olarak yayımlar"))
    .addSubcommand((sub) => sub.setName("tur-oynat").setDescription("İki açık zar tamamlanınca savaş turunu çözer"))
    .addSubcommand((sub) => sub.setName("ordu-detay").setDescription("Tam birlik kompozisyonunu yalnızca yöneticiye gösterir"))
    .addSubcommand((sub) => sub.setName("kayip-raporu").setDescription("Son savaşın belgeye işlenen ayrıntılı kayıp raporunu yalnızca yöneticiye gösterir"))
    .addSubcommand((sub) => sub.setName("bitir").setDescription("Savaşı yönetici kararıyla sonuçlandırır")
      .addStringOption((o) => o.setName("galip").setDescription("Galip taraf").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }, { name: "Galip Yok", value: "NONE" }))
      .addStringOption((o) => o.setName("neden").setDescription("Herkese açık sonuç açıklaması").setRequired(true).setMaxLength(500)))
    .addSubcommand((sub) => sub.setName("iptal").setDescription("Etkin savaşı iptal eder")),
  new SlashCommandBuilder()
    .setName("yonetim").setDescription("Oyun yöneticisi komutları")
    .addSubcommand((sub) => sub.setName("ulke-olustur").setDescription("Yeni ülke oluşturur")
      .addStringOption((o) => o.setName("ad").setDescription("Ülke adı").setRequired(true))
      .addIntegerOption((o) => o.setName("hazine").setDescription("Başlangıç hazinesi").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("oyuncu-ata").setDescription("Oyuncuyu ülkeye atar")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addUserOption((o) => o.setName("oyuncu").setDescription("Oyuncu").setRequired(true)))
    .addSubcommand((sub) => sub.setName("oyuncu-cikar").setDescription("Oyuncunun ülke atamasını kaldırır")
      .addStringOption((o) => o.setName("ulke").setDescription("Oyuncunun çıkarılacağı ülke").setRequired(true))
      .addUserOption((o) => o.setName("oyuncu").setDescription("Ülkeden çıkarılacak oyuncu").setRequired(true)))
    .addSubcommand((sub) => sub.setName("yerleske-ekle").setDescription("Ülkeye yerleşke ekler")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addStringOption((o) => o.setName("ad").setDescription("Yerleşke adı").setRequired(true))
      .addIntegerOption((o) => o.setName("nufus").setDescription("Özgür nüfus").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("kole").setDescription("Köle nüfusu").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("gelir").setDescription("Temel yerleşke geliri").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("vergi-geliri").setDescription("Temel vergi geliri").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("kara-ticareti").setDescription("Temel kara ticareti geliri").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("deniz-ticareti").setDescription("Temel deniz ticareti geliri").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("nufus-artisi").setDescription("Alım Turu temel nüfus artışı").setMinValue(0).setRequired(true))
      .addStringOption((o) => o.setName("hammadde").setDescription("Yerleşkenin ürettiği hammadde").setRequired(true).addChoices(...RESOURCE_CHOICES)))
    .addSubcommand((sub) => sub.setName("hammadde-ayarla").setDescription("Mevcut yerleşkenin hammaddesini değiştirir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Yerleşke adı").setRequired(true))
      .addStringOption((o) => o.setName("hammadde").setDescription("Yeni hammadde").setRequired(true).addChoices(...RESOURCE_CHOICES)))
    .addSubcommand((sub) => sub.setName("tur-ilerlet").setDescription("Yeni turu açar ve bütün otomasyonları işler"))
    .addSubcommand((sub) => sub.setName("tur-durumu").setDescription("Turun hareket durumunu değiştirir")
      .addStringOption((o) => o.setName("durum").setDescription("Yeni durum").setRequired(true)
        .addChoices({ name: "Açık", value: "OPEN" }, { name: "Kapalı", value: "CLOSED" }, { name: "Olaylar çözülüyor", value: "RESOLVING" })))
    .addSubcommand((sub) => sub.setName("hazine").setDescription("Ülke hazinesini artırır veya azaltır")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Negatif değer kullanılabilir").setRequired(true))
      .addStringOption((o) => o.setName("neden").setDescription("İşlem açıklaması").setRequired(true)))
    .addSubcommand((sub) => sub.setName("harap").setDescription("Yerleşkenin harap durumunu değiştirir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Yerleşke adı").setRequired(true))
      .addBooleanOption((o) => o.setName("harap").setDescription("Harap mı?").setRequired(true)))
    .addSubcommand((sub) => sub.setName("oyunu-sifirla").setDescription("Bu sunucudaki bütün oyun verilerini kalıcı olarak siler")
      .addStringOption((o) => o.setName("onay").setDescription("Onaylamak için büyük harflerle SIFIRLA yazın").setRequired(true)))
    .addSubcommand((sub) => sub.setName("komut-log-kanali").setDescription("Oyuncu bot komutlarının aktarılacağı kanalı ayarlar")
      .addStringOption((o) => o.setName("islem").setDescription("İşlem").setRequired(true).addChoices({ name: "Ayarla", value: "set" }, { name: "Kapat", value: "clear" }))
      .addChannelOption((o) => o.setName("kanal").setDescription("Komut kayıt kanalı").addChannelTypes(ChannelType.GuildText)))
    .addSubcommand((sub) => sub.setName("komut-gecmisi").setDescription("Son oyuncu bot komutlarını gösterir")
      .addIntegerOption((o) => o.setName("adet").setDescription("Gösterilecek kayıt sayısı").setMinValue(1).setMaxValue(25)))
    .addSubcommand((sub) => sub.setName("rol-rapor-kanali").setDescription("Günlük rol sıralamasının gönderileceği kanalı ayarlar")
      .addStringOption((o) => o.setName("islem").setDescription("İşlem").setRequired(true).addChoices({ name: "Ayarla", value: "set" }, { name: "Kapat", value: "clear" }))
      .addChannelOption((o) => o.setName("kanal").setDescription("Günlük rapor kanalı").addChannelTypes(ChannelType.GuildText)))
    .addSubcommand((sub) => sub.setName("rol-kanali").setDescription("Kelime sayılacak rol kanalını ekler veya kaldırır")
      .addStringOption((o) => o.setName("islem").setDescription("İşlem").setRequired(true).addChoices({ name: "Ekle", value: "add" }, { name: "Kaldır", value: "remove" }))
      .addChannelOption((o) => o.setName("kanal").setDescription("Rol kanalı").addChannelTypes(ChannelType.GuildText).setRequired(true)))
].map((builder) => builder.toJSON());

export const buildingChoices = Object.values(BUILDINGS);
export const unitChoices = Object.entries(UNITS).filter(([key]) => key !== "observer");
export const shipChoices = Object.entries(SHIPS);
