import { ChannelType, SlashCommandBuilder } from "discord.js";
import { BUILDINGS, CHARACTER_ROLES, CITY_POLICIES, MOBILIZATION_RULES, SHIPS, SIEGE_ASSETS, UNITS } from "../domain/catalog.js";
import { RESOURCE_CHOICES } from "../domain/resources.js";
import { SETTLEMENT_EVENT_TYPES } from "../domain/events.js";
import { BATTLE_TERRAINS, BATTLE_UNIT_STATS, NAVAL_UNIT_STATS, SIEGE_ASSET_BATTLE_STATS } from "../domain/battle.js";
import { NPC_AUTO_PURCHASE_DOCTRINES } from "../domain/npc-auto-purchase.js";
import { SPECIAL_UNITS } from "../domain/special-units.js";

const countryOption = (option: any) => option.setName("ulke").setDescription("Yalnızca DM: işlem yapılacak ülke").setRequired(false);
const CHARACTER_ROLE_CHOICES = Object.entries(CHARACTER_ROLES).map(([value, role]) => ({ name: role.label, value }));
const SETTLEMENT_EVENT_CHOICES = Object.entries(SETTLEMENT_EVENT_TYPES).map(([value, event]) => ({ name: event.label, value }));

export const commandBuilders = [
  new SlashCommandBuilder()
    .setName("belge").setDescription("Ülkenin güncel belgesini gösterir")
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("devlet-bilgisi").setDescription("Bir devletin herkese açık, askerî ve ekonomik bilgi içermeyen profilini gösterir")
    .addStringOption((option) => option.setName("ulke").setDescription("Görüntülenecek devletin adı").setRequired(true)),
  new SlashCommandBuilder()
    .setName("diplomasi-kanali").setDescription("Yalnızca yönetici: ittifak ve pakt davet kanalını ayarlar")
    .addStringOption((option) => option.setName("islem").setDescription("Kanal işlemi").setRequired(true)
      .addChoices({ name: "Ayarla", value: "set" }, { name: "Kapat", value: "clear" }))
    .addChannelOption((option) => option.setName("kanal").setDescription("İttifak ve pakt davetlerinin gönderileceği metin kanalı")
      .addChannelTypes(ChannelType.GuildText)),
  new SlashCommandBuilder()
    .setName("savas-ilan-kanali").setDescription("Yalnızca yönetici: resmî savaş ve barış duyurularının kanalını ayarlar")
    .addStringOption((option) => option.setName("islem").setDescription("Kanal işlemi").setRequired(true)
      .addChoices({ name: "Ayarla", value: "set" }, { name: "Kapat", value: "clear" }))
    .addChannelOption((option) => option.setName("kanal").setDescription("Savaş ilanları ve barış duyurularının gönderileceği metin kanalı")
      .addChannelTypes(ChannelType.GuildText)),
  new SlashCommandBuilder()
    .setName("hos-geldin").setDescription("Yalnızca yönetici: yeni üye karşılama kanalını ve mesajını ayarlar")
    .addStringOption((option) => option.setName("islem").setDescription("İşlem").setRequired(true)
      .addChoices({ name: "Ayarla", value: "set" }, { name: "Kapat", value: "clear" }))
    .addChannelOption((option) => option.setName("kanal").setDescription("Hoş geldin mesajlarının gönderileceği kanal").addChannelTypes(ChannelType.GuildText))
    .addStringOption((option) => option.setName("mesaj").setDescription("İsteğe bağlı metin; {uye} ve {sunucu} kullanılabilir").setMaxLength(1500)),
  new SlashCommandBuilder()
    .setName("devlet-rolleri").setDescription("Yalnızca yönetici: eksik devlet rollerini oluşturur ve üyelikleri eşitler"),
  new SlashCommandBuilder()
    .setName("ulke-formla").setDescription("Yalnızca yönetici: devleti kurulabilir ülkeye dönüştürür ve bonuslarını açar")
    .addStringOption((option) => option.setName("mevcut-ulke").setDescription("Formlanacak mevcut devletin tam adı").setRequired(true))
    .addStringOption((option) => option.setName("formlanan-ulke").setDescription("Kurulacak ülkeyi yazmaya başlayarak seçin").setRequired(true).setAutocomplete(true)),
  new SlashCommandBuilder()
    .setName("ozel-birlik-yetkisi").setDescription("Yalnızca yönetici: ülkelere özel birlik erişimi verir veya kaldırır")
    .addSubcommand((sub) => sub.setName("ayarla").setDescription("Bir ülkenin özel birlik erişimini değiştirir")
      .addStringOption((o) => o.setName("ulke").setDescription("Yetkisi değiştirilecek ülke").setRequired(true))
      .addStringOption((o) => o.setName("birlik").setDescription("Özel birlik türü").setRequired(true)
        .addChoices(...Object.entries(SPECIAL_UNITS).map(([value, unit]) => ({ name: unit.name, value }))))
      .addStringOption((o) => o.setName("islem").setDescription("Erişim işlemi").setRequired(true).addChoices(
        { name: "Erişim aç", value: "UNLOCK" },
        { name: "Erişimi kaldır", value: "LOCK" }
      )))
    .addSubcommand((sub) => sub.setName("listele").setDescription("Bir ülkeye açık özel birlikleri gösterir")
      .addStringOption((o) => o.setName("ulke").setDescription("Görüntülenecek ülke").setRequired(true))),
  new SlashCommandBuilder()
    .setName("savas-ilani").setDescription("Bir devlete resmî savaş ilan eder ve savaşlar kanalında duyurur")
    .addStringOption((option) => option.setName("hedef-ulke").setDescription("Savaş ilan edilecek devlet").setRequired(true))
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("baris-teklifi").setDescription("Savaşta olduğunuz devlete şartlı veya tazminatlı barış teklif eder")
    .addStringOption((option) => option.setName("hedef-ulke").setDescription("Barış teklif edilecek savaş tarafı").setRequired(true))
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("aktif-savaslar").setDescription("Devam eden bütün resmî devlet savaşlarını herkese açık listeler"),
  new SlashCommandBuilder()
    .setName("savas-sonlandir").setDescription("Yalnızca yönetici: aktif bir savaşı sonuçlandırır ve herkese duyurur")
    .addStringOption((option) => option.setName("savas").setDescription("Sonlandırılacak aktif savaşı yazmaya başlayarak seçin").setRequired(true).setAutocomplete(true))
    .addStringOption((option) => option.setName("kazanan").setDescription("Kazanan devlet; kazanan yoksa Beyaz Barış").setRequired(true).setAutocomplete(true))
    .addStringOption((option) => option.setName("aciklama").setDescription("Herkese açık savaş bitiş açıklaması").setRequired(true).setMinLength(2).setMaxLength(2000)),
  new SlashCommandBuilder()
    .setName("ittifak").setDescription("İki devlet arasındaki karşılıklı müttefikliği yönetir")
    .addSubcommand((sub) => sub.setName("teklif").setDescription("Başka bir devlete ittifak daveti gönderir")
      .addStringOption((option) => option.setName("hedef-ulke").setDescription("Davet edilecek devlet").setRequired(true))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("liste").setDescription("Aktif ittifakları ve bekleyen ittifak davetlerini gösterir")
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("feshet").setDescription("Başka bir devletle mevcut ittifakı sona erdirir")
      .addStringOption((option) => option.setName("hedef-ulke").setDescription("İttifakı sona erecek devlet").setRequired(true))
      .addStringOption(countryOption)),
  new SlashCommandBuilder()
    .setName("pakt").setDescription("Birden fazla devletin katılabileceği diplomatik paktları yönetir")
    .addSubcommand((sub) => sub.setName("olustur").setDescription("Amacı ve açıklaması belirlenen yeni bir pakt oluşturur")
      .addStringOption((option) => option.setName("ad").setDescription("Paktın adı").setRequired(true).setMinLength(2).setMaxLength(80))
      .addStringOption((option) => option.setName("amac").setDescription("Paktın temel amacı").setRequired(true).setMinLength(2).setMaxLength(200))
      .addStringOption((option) => option.setName("aciklama").setDescription("Paktın ayrıntılı açıklaması").setRequired(true).setMinLength(2).setMaxLength(1000))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("davet").setDescription("Bir devleti kurucusu olduğunuz pakta davet eder")
      .addStringOption((option) => option.setName("pakt").setDescription("Paktın adı").setRequired(true))
      .addStringOption((option) => option.setName("hedef-ulke").setDescription("Davet edilecek devlet").setRequired(true))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("davetlerim").setDescription("Devletinize gönderilen bekleyen pakt davetlerini gösterir")
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("bilgi").setDescription("Paktın amacını, açıklamasını ve üye devletlerini herkese gösterir")
      .addStringOption((option) => option.setName("pakt").setDescription("Görüntülenecek paktın adı").setRequired(true)))
    .addSubcommand((sub) => sub.setName("liste").setDescription("Sunucudaki bütün paktları herkese açık olarak listeler"))
    .addSubcommand((sub) => sub.setName("ayril").setDescription("Üyesi olduğunuz bir pakttan ayrılır")
      .addStringOption((option) => option.setName("pakt").setDescription("Ayrılınacak paktın adı").setRequired(true))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("uye-cikar").setDescription("Kurucusu olduğunuz pakttan bir devleti çıkarır")
      .addStringOption((option) => option.setName("pakt").setDescription("Paktın adı").setRequired(true))
      .addStringOption((option) => option.setName("hedef-ulke").setDescription("Üyelikten çıkarılacak devlet").setRequired(true))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("lider-devret").setDescription("Pakt liderliğini mevcut üye bir devlete devreder")
      .addStringOption((option) => option.setName("pakt").setDescription("Paktın adı").setRequired(true))
      .addStringOption((option) => option.setName("hedef-ulke").setDescription("Yeni lider olacak üye devlet").setRequired(true))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("dagit").setDescription("Kurucusu olduğunuz paktı ve bütün davetlerini kalıcı olarak kaldırır")
      .addStringOption((option) => option.setName("pakt").setDescription("Dağıtılacak paktın adı").setRequired(true))
      .addStringOption((option) => option.setName("onay").setDescription("Onaylamak için büyük harflerle DAGIT yazın").setRequired(true))
      .addStringOption(countryOption)),
  new SlashCommandBuilder()
    .setName("alim").setDescription("Yerleşkede etkileşimli bina alımı başlatır")
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("asker-alimi").setDescription("Etkileşimli asker alımı başlatır")
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("asker-terhis").setDescription("Yerleşkedeki mevcut askerleri kalıcı olarak terhis eder")
    .addStringOption((option) => option.setName("yerleske").setDescription("Birliğin bulunduğu yerleşke").setRequired(true))
    .addStringOption((option) => option.setName("birim").setDescription("Terhis edilecek birlik türü").setRequired(true)
      .addChoices(...Object.entries(UNITS).map(([value, unit]) => ({ name: unit.name, value }))))
    .addStringOption((option) => option.setName("durum").setDescription("Birliğin mevcut konumu").setRequired(true)
      .addChoices({ name: "Garnizon", value: "GARRISON" }, { name: "Dost Bölgede Sefer", value: "FIELD_FRIENDLY" }, { name: "Düşman Bölgesinde Sefer", value: "FIELD_HOSTILE" }))
    .addIntegerOption((option) => option.setName("miktar").setDescription("Terhis edilecek asker sayısı").setMinValue(1).setRequired(true))
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("gemi-alimi").setDescription("Etkileşimli gemi alımı başlatır")
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("gozcu-alimi").setDescription("Yerleşkeye bir Gözcü Birliği alır")
    .addStringOption((option) => option.setName("yerleske").setDescription("Gözcünün bağlı olacağı yerleşke").setRequired(true))
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("kusatma-uretimi").setDescription("Mühendislik Atölyesinde kuşatma aleti üretir")
    .addStringOption((option) => option.setName("yerleske").setDescription("Üretim yapacak yerleşke").setRequired(true))
    .addStringOption((option) => option.setName("alet").setDescription("Üretilecek kuşatma aleti").setRequired(true)
      .addChoices(...Object.entries(SIEGE_ASSETS).filter(([key]) => !["ladder_group","ram"].includes(key)).map(([value, asset]) => ({ name: asset.name, value }))))
    .addIntegerOption((option) => option.setName("miktar").setDescription("Üretilecek adet").setMinValue(1).setRequired(true))
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("alim-iptal").setDescription("Yalnızca yönetici: hatalı bekleyen alımı iptal eder ve ücretini iade eder")
    .addStringOption((option) => option.setName("siparis").setDescription("İptal edilecek bekleyen alımı yazmaya başlayarak seçin").setRequired(true).setAutocomplete(true)),
  new SlashCommandBuilder()
    .setName("gelir-cezasi").setDescription("Yalnızca yönetici: yerleşkeye süreli yüzdelik gelir cezası uygular")
    .addSubcommand((sub) => sub.setName("uygula").setDescription("Sonraki Alım Turundan başlayacak gelir cezasını ayarlar")
      .addStringOption((option) => option.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((option) => option.setName("yerleske").setDescription("Geliri azaltılacak yerleşke").setRequired(true))
      .addIntegerOption((option) => option.setName("yuzde").setDescription("Toplam gelirden eksiltilecek yüzde").setMinValue(1).setMaxValue(100).setRequired(true))
      .addIntegerOption((option) => option.setName("alim-turu").setDescription("Cezanın uygulanacağı Alım Turu sayısı").setMinValue(1).setMaxValue(100).setRequired(true))
      .addStringOption((option) => option.setName("neden").setDescription("Olay veya ceza açıklaması").setMinLength(1).setMaxLength(500).setRequired(true)))
    .addSubcommand((sub) => sub.setName("kaldir").setDescription("Yerleşkedeki etkin gelir cezasını erken kaldırır")
      .addStringOption((option) => option.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((option) => option.setName("yerleske").setDescription("Cezası kaldırılacak yerleşke").setRequired(true))),
  new SlashCommandBuilder()
    .setName("seferberlik").setDescription("Ülkenin seferberlik seviyesini değiştirir")
    .addStringOption((option) => option.setName("seviye").setDescription("Yeni seferberlik seviyesi").setRequired(true)
      .addChoices(...Object.entries(MOBILIZATION_RULES).map(([value, rule]) => ({ name: rule.label, value }))))
    .addStringOption(countryOption),
  new SlashCommandBuilder()
    .setName("ticaret").setDescription("Ülkeler arası hammadde ticaretini yönetir")
    .addSubcommand((sub) => sub.setName("teklif").setDescription("Bir ülkenin yerleşkesine kaynak ticareti teklif eder")
      .addStringOption((o) => o.setName("hedef-ulke").setDescription("Teklif gönderilecek ülke").setRequired(true))
      .addStringOption((o) => o.setName("kendi-yerlesken").setDescription("Kaynak gönderecek yerleşkeniz").setRequired(true))
      .addStringOption((o) => o.setName("hedef-yerleske").setDescription("Karşı tarafın kaynak gönderecek yerleşkesi").setRequired(true))
      .addStringOption((o) => o.setName("tur").setDescription("Ticaret güzergâhı").setRequired(true).addChoices({ name: "Kara Ticareti", value: "LAND" }, { name: "Deniz Ticareti", value: "SEA" }))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("liste").setDescription("Bekleyen ve aktif kaynak ticaretlerini gösterir")
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("feshet").setDescription("Aktif antlaşmalar arasından feshedilecek olanı seçtirir")
      .addStringOption(countryOption)),
  new SlashCommandBuilder()
    .setName("tur").setDescription("Resmî tur durumunu yönetir ve herkese açık duyuru yayımlar")
    .addSubcommand((sub) => sub.setName("atla").setDescription("Sonraki tura geçer ve yeni turu açar"))
    .addSubcommand((sub) => sub.setName("ac").setDescription("Mevcut turu oyuncu hareketlerine açar"))
    .addSubcommand((sub) => sub.setName("durdur").setDescription("Oyuncu hareketlerini durdurup olay çözümüne geçer"))
    .addSubcommand((sub) => sub.setName("kapat").setDescription("Mevcut turu tamamen kapatır")),
  new SlashCommandBuilder()
    .setName("politika").setDescription("Yerleşkenin Curia şehir politikalarını yönetir")
    .addSubcommand((sub) => sub.setName("uygula").setDescription("Bir politika değişimini başlatır; bir sonraki tur etkinleşir")
      .addStringOption((o) => o.setName("yerleske").setDescription("Politikanın uygulanacağı yerleşke").setRequired(true))
      .addStringOption((o) => o.setName("politika").setDescription("Uygulanacak şehir politikası").setRequired(true)
        .addChoices(...Object.entries(CITY_POLICIES).map(([value, policy]) => ({ name: policy.label, value }))))
      .addIntegerOption((o) => o.setName("yuva").setDescription("Politika yuvası").setRequired(true).addChoices({ name: "1. Politika", value: 1 }, { name: "2. Politika", value: 2 }))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("kaldir").setDescription("Seçilen politika yuvasını boşaltır")
      .addStringOption((o) => o.setName("yerleske").setDescription("Politikanın bağlı olduğu yerleşke").setRequired(true))
      .addIntegerOption((o) => o.setName("yuva").setDescription("Boşaltılacak politika yuvası").setRequired(true).addChoices({ name: "1. Politika", value: 1 }, { name: "2. Politika", value: 2 }))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("liste").setDescription("Ülkenin yerleşke politikalarını gösterir")
      .addStringOption(countryOption)),
  new SlashCommandBuilder()
    .setName("akademi").setDescription("Akademi karakter eğitimini ve görev atamalarını yönetir")
    .addSubcommand((sub) => sub.setName("egit").setDescription("Akademinin bu Alım Turundaki karakter eğitimini başlatır")
      .addStringOption((o) => o.setName("yerleske").setDescription("Karakteri yetiştirecek Akademi").setRequired(true))
      .addStringOption((o) => o.setName("elenen-gorev").setDescription("Yalnız Akademi Sv2: zar havuzundan çıkarılacak görev").addChoices(...CHARACTER_ROLE_CHOICES))
      .addStringOption((o) => o.setName("secilen-gorev").setDescription("Yalnız Akademi Sv3: doğrudan yetiştirilecek görev").addChoices(...CHARACTER_ROLE_CHOICES))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("karakterler").setDescription("Ülkenin yetişmiş karakterlerini listeler")
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("ata").setDescription("Yetişmiş karakteri uygun bir yerleşke binasına atar")
      .addStringOption((o) => o.setName("karakter").setDescription("Karakterin tam adı").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Atanacağı yerleşke").setRequired(true))
      .addStringOption((o) => o.setName("gorev-yeri").setDescription("Atanacağı bina").setRequired(true).addChoices({ name: "Curia", value: "CURIA" }, { name: "Agora / Forum", value: "AGORA" }))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("gorevden-al").setDescription("Karakterin bina atamasını kaldırır")
      .addStringOption((o) => o.setName("karakter").setDescription("Karakterin tam adı").setRequired(true))
      .addStringOption(countryOption)),
  new SlashCommandBuilder()
    .setName("panteon").setDescription("Panteon Sv3 savaş dönemi kredisini yönetir")
    .addSubcommand((sub) => sub.setName("kredi-al").setDescription("Son Alım Turu geliri sınırında faizsiz kredi alır")
      .addStringOption((o) => o.setName("yerleske").setDescription("Panteon Sv3 bulunan yerleşke").setRequired(true))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Kredi miktarı").setMinValue(1).setRequired(true))
      .addStringOption(countryOption))
    .addSubcommand((sub) => sub.setName("kredi-ode").setDescription("Aktif Panteon kredisine geri ödeme yapar")
      .addIntegerOption((o) => o.setName("miktar").setDescription("Geri ödeme miktarı").setMinValue(1).setRequired(true))
      .addStringOption(countryOption)),
  new SlashCommandBuilder()
    .setName("olay").setDescription("Yalnızca oyun yöneticisi: ağırlıklı yerleşke olaylarını seçer ve uygular")
    .addSubcommand((sub) => sub.setName("sec").setDescription("Tüm sunucudaki uygun yerleşkeler arasından ağırlıklı olay seçer")
      .addStringOption((o) => o.setName("tur").setDescription("Seçilecek olay türü").setRequired(true).addChoices(...SETTLEMENT_EVENT_CHOICES))
      .addStringOption((o) => o.setName("ulke").setDescription("İsteğe bağlı: yalnızca bu ülkenin yerleşkelerini tarar")))
    .addSubcommand((sub) => sub.setName("riskler").setDescription("Tüm yerleşkelerin olay ağırlıklarını ve koruma nedenlerini listeler")
      .addStringOption((o) => o.setName("tur").setDescription("Listelenecek olay türü").setRequired(true).addChoices(...SETTLEMENT_EVENT_CHOICES))
      .addStringOption((o) => o.setName("ulke").setDescription("İsteğe bağlı: yalnızca bu ülkenin yerleşkelerini gösterir")))
    .addSubcommand((sub) => sub.setName("uygula").setDescription("Bekleyen olay seçimini veya belirttiğiniz yerleşkeye olayı uygular")
      .addStringOption((o) => o.setName("tur").setDescription("Uygulanacak olay türü").setRequired(true).addChoices(...SETTLEMENT_EVENT_CHOICES))
      .addStringOption((o) => o.setName("ulke").setDescription("İsteğe bağlı: elle olay uygulanacak ülke"))
      .addStringOption((o) => o.setName("yerleske").setDescription("İsteğe bağlı: elle olay uygulanacak yerleşke")))
    .addSubcommand((sub) => sub.setName("sonlandir").setDescription("Yerleşkede aktif olan bir olayı sonlandırır")
      .addStringOption((o) => o.setName("tur").setDescription("Sonlandırılacak olay türü").setRequired(true).addChoices(...SETTLEMENT_EVENT_CHOICES))
      .addStringOption((o) => o.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Olayın sonlanacağı yerleşke").setRequired(true)))
    .addSubcommand((sub) => sub.setName("salgin").setDescription("Panteon ve Zeytin etkilerini uygulayarak salgın zarı atar")
      .addStringOption((o) => o.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Olayın yaşanacağı yerleşke").setRequired(true))
      .addIntegerOption((o) => o.setName("baz-risk").setDescription("Temel salgın riski yüzdesi").setMinValue(0).setMaxValue(100).setRequired(true)))
    .addSubcommand((sub) => sub.setName("salgin-iyilesme").setDescription("Su Kemeri bonusuyla 1d20 salgın iyileşme zarı atar")
      .addStringOption((o) => o.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("İyileşme zarı atacak yerleşke").setRequired(true)))
    .addSubcommand((sub) => sub.setName("karaborsa").setDescription("Agora Sv3 tüccarının karaborsa olayını engelleyip engellemediğini denetler")
      .addStringOption((o) => o.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Olayın yaşanacağı yerleşke").setRequired(true))),
  new SlashCommandBuilder()
    .setName("zar").setDescription("Zar atar")
    .addIntegerOption((option) => option.setName("adet").setDescription("Zar adedi").setMinValue(1).setMaxValue(20).setRequired(true))
    .addIntegerOption((option) => option.setName("yuz").setDescription("Zarın yüz sayısı").setMinValue(2).setMaxValue(10_000).setRequired(true))
    .addIntegerOption((option) => option.setName("bonus").setDescription("Sonuca eklenecek bonus").setMinValue(-10_000).setMaxValue(10_000))
    .addBooleanOption((option) => option.setName("gizli").setDescription("Sonucu yalnızca sen gör")),
  new SlashCommandBuilder()
    .setName("rol-siralama").setDescription("Rol kanallarındaki kelime sıralamasını gösterir")
    .addStringOption((option) => option.setName("donem").setDescription("Sıralama dönemi").setRequired(true)
      .addChoices({ name: "Son 24 saat", value: "daily" }, { name: "Son 7 gün", value: "weekly" })),
  new SlashCommandBuilder()
    .setName("parali-bakim-topla").setDescription("Yalnızca yönetici: bu turun vadesi gelen tüm paralı asker bakımlarını toplar"),
  new SlashCommandBuilder()
    .setName("parali-asker").setDescription("Yalnızca yönetici: paralı asker sözleşmelerini yönetir")
    .addSubcommand((sub) => sub.setName("kirala").setDescription("Bir paralı asker grubunu kiralar")
      .addStringOption((o) => o.setName("ulke").setDescription("Sözleşmeyi yapacak ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Birliğin ulaşacağı yerleşke").setRequired(true))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true)))
    .addSubcommand((sub) => sub.setName("ucretsiz-ekle").setDescription("Manuel ücreti önceden alınmış şirketi yalnız bakım işleyecek şekilde ekler")
      .addStringOption((o) => o.setName("ulke").setDescription("Şirketin bağlı olacağı ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Şirketin bulunduğu yerleşke").setRequired(true))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true)))
    .addSubcommand((sub) => sub.setName("listele").setDescription("Bir ülkenin canlı sözleşmelerini gösterir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke").setRequired(true)))
    .addSubcommand((sub) => sub.setName("uzat").setDescription("Sözleşmeyi 3 tur uzatır")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke").setRequired(true))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true)))
    .addSubcommand((sub) => sub.setName("bakim-ode").setDescription("Bu tur ödenemeyen bakımı sonradan öder")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke").setRequired(true))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true)))
    .addSubcommand((sub) => sub.setName("feshet").setDescription("Sözleşmeyi sona erdirir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke").setRequired(true))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true)))
    .addSubcommand((sub) => sub.setName("tasi").setDescription("Etkin grubu başka bir dost yerleşkeye taşır")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke").setRequired(true))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Hedef yerleşke").setRequired(true)))
    .addSubcommand((sub) => sub.setName("mevcut-duzelt").setDescription("Kayıp veya yönetici kararı sonrası şirket mevcudunu düzeltir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke").setRequired(true))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true))
      .addStringOption((o) => o.setName("tur").setDescription("Kayıt türü").setRequired(true).addChoices(
        { name: "Kara Birliği", value: "UNIT" }, { name: "Gemi", value: "SHIP" }, { name: "Kuşatma Aleti", value: "ASSET" }
      ))
      .addStringOption((o) => o.setName("kalem").setDescription("Birim, gemi veya alet").setRequired(true).setAutocomplete(true))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Yeni mevcut").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("kayip-ekle").setDescription("Bir paralı asker kampanyasından kara birliği kaybı düşer")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke").setRequired(true))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true))
      .addStringOption((o) => o.setName("kalem").setDescription("Kayıp verilecek kara birliği").setRequired(true).addChoices(...Object.entries(UNITS).filter(([key]) => !["observer", "militia"].includes(key) && !(key in SPECIAL_UNITS)).map(([value, unit]) => ({ name: unit.name, value }))))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Düşülecek asker sayısı").setMinValue(1).setRequired(true))),
  new SlashCommandBuilder()
    .setName("savas").setDescription("Kalıcılığa sahip açık zar savaş sistemini yönetir")
    .addSubcommand((sub) => sub.setName("baslat").setDescription("Bu kanalda yeni savaş taslağı oluşturur")
      .addStringOption((o) => o.setName("taraf-a").setDescription("A tarafındaki ülke").setRequired(true))
      .addStringOption((o) => o.setName("taraf-b").setDescription("B tarafındaki ülke").setRequired(true))
      .addStringOption((o) => o.setName("arazi").setDescription("Savaş alanı hazır ayarı").setRequired(true).addChoices(...Object.entries(BATTLE_TERRAINS).map(([value, terrain]) => ({ name: terrain.label, value }))))
      .addStringOption((o) => o.setName("kontrol-a").setDescription("A tarafının zar yetkisi").setRequired(true).addChoices({ name: "Ülke Oyuncuları", value: "PLAYERS" }, { name: "Oyun Yöneticisi / NPC", value: "GM" }))
      .addStringOption((o) => o.setName("kontrol-b").setDescription("B tarafının zar yetkisi").setRequired(true).addChoices({ name: "Ülke Oyuncuları", value: "PLAYERS" }, { name: "Oyun Yöneticisi / NPC", value: "GM" }))
      .addStringOption((o) => o.setName("savunulan-yerleske").setDescription("Yalnız kuşatmada: B tarafının savunduğu yerleşke"))
      .addStringOption((o) => o.setName("anlatim").setDescription("Herkese açık savaş açılış metni").setMaxLength(1000)))
    .addSubcommand((sub) => sub.setName("taraf-ulke").setDescription("Savaş tarafına koalisyon ülkesi ekler veya çıkarır")
      .addStringOption((o) => o.setName("taraf").setDescription("Ülkenin katılacağı savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addStringOption((o) => o.setName("islem").setDescription("İşlem").setRequired(true).addChoices({ name: "Ekle", value: "ADD" }, { name: "Çıkar", value: "REMOVE" }))
      .addStringOption((o) => o.setName("ulke").setDescription("Eklenecek veya çıkarılacak ülke").setRequired(true)))
    .addSubcommand((sub) => sub.setName("birlik-ayarla").setDescription("Taslağın gizli birlik kadrosuna bir birlik yazar")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addStringOption((o) => o.setName("birim").setDescription("Birim türü").setRequired(true).addChoices(...Object.entries(BATTLE_UNIT_STATS).map(([value, unit]) => ({ name: unit.label, value }))))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Bu türden asker sayısı; silmek için 0").setMinValue(0).setRequired(true))
      .addStringOption((o) => o.setName("ulke").setDescription("Koalisyonda kadrosu düzenlenecek ülke; boşsa ana ülke")))
    .addSubcommand((sub) => sub.setName("kadro-ayarla").setDescription("Bir tarafın bütün kara ordusu kadrosunu tek komutla yazar")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addIntegerOption((o) => o.setName("hafif-piyade").setDescription("Hafif Piyade / Ciritçi").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("sapanci").setDescription("Sapancı").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("mizrakli").setDescription("Mızraklı Piyade").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("okcu").setDescription("Okçu").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("agir-piyade").setDescription("Ağır Piyade").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("hafif-suvari").setDescription("Hafif Süvari").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("agir-suvari").setDescription("Ağır Süvari").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("milis").setDescription("Kalıcı Milis").setMinValue(0))
      .addIntegerOption((o) => o.setName("lejyoner").setDescription("Lejyoner").setMinValue(0))
      .addIntegerOption((o) => o.setName("hoplit").setDescription("Hoplit").setMinValue(0))
      .addIntegerOption((o) => o.setName("atli-okcu").setDescription("Atlı Okçu").setMinValue(0))
      .addIntegerOption((o) => o.setName("deve-suvarisi").setDescription("Deve Süvarisi").setMinValue(0))
      .addIntegerOption((o) => o.setName("briton-uzun-yayci").setDescription("Briton Uzun Yaycıları").setMinValue(0))
      .addStringOption((o) => o.setName("ulke").setDescription("Koalisyonda kadrosu düzenlenecek ülke; boşsa ana ülke")))
    .addSubcommand((sub) => sub.setName("gemi-ayarla").setDescription("Deniz savaşı taslağının gizli gemi kadrosunu düzenler")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addStringOption((o) => o.setName("gemi").setDescription("Gemi türü").setRequired(true).addChoices(...Object.entries(NAVAL_UNIT_STATS).map(([value, unit]) => ({ name: unit.label, value }))))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Gemi sayısı; silmek için 0").setMinValue(0).setRequired(true))
      .addStringOption((o) => o.setName("ulke").setDescription("Koalisyonda filosu düzenlenecek ülke; boşsa ana ülke")))
    .addSubcommand((sub) => sub.setName("filo-ayarla").setDescription("Bir tarafın bütün filosunu tek komutla yazar")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addIntegerOption((o) => o.setName("kerkouros").setDescription("Kerkouros sayısı").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("trireme").setDescription("Trireme sayısı").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("quinquereme").setDescription("Quinquereme sayısı").setMinValue(0).setRequired(true))
      .addStringOption((o) => o.setName("ulke").setDescription("Koalisyonda filosu düzenlenecek ülke; boşsa ana ülke")))
    .addSubcommand((sub) => sub.setName("kusatma-aleti-ayarla").setDescription("Kuşatma taslağının gizli savaş aletlerini düzenler")
      .addStringOption((o) => o.setName("taraf").setDescription("A saldıran, B savunandır").setRequired(true).addChoices({ name: "A — Kuşatan", value: "A" }, { name: "B — Savunan", value: "B" }))
      .addStringOption((o) => o.setName("alet").setDescription("Kuşatma aleti").setRequired(true).addChoices(...Object.entries(SIEGE_ASSET_BATTLE_STATS).map(([value, asset]) => ({ name: asset.label, value }))))
      .addStringOption((o) => o.setName("hedef").setDescription("Aletin bu savaşta vuracağı hedef").setRequired(true).addChoices({ name: "Sur", value: "WALL" }, { name: "Kapı", value: "GATE" }, { name: "Düşman Ordusu", value: "ARMY" }, { name: "Hücum Desteği", value: "ASSAULT" }))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Alet sayısı; silmek için 0").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("parali-asker-ayarla").setDescription("Etkin bir paralı asker şirketini savaş taslağına ekler veya çıkarır")
      .addStringOption((o) => o.setName("taraf").setDescription("Savaş tarafı").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }))
      .addStringOption((o) => o.setName("islem").setDescription("İşlem").setRequired(true).addChoices({ name: "Ekle", value: "ADD" }, { name: "Çıkar", value: "REMOVE" }))
      .addStringOption((o) => o.setName("sirket").setDescription("Paralı asker grubu").setRequired(true).setAutocomplete(true)))
    .addSubcommand((sub) => sub.setName("saha-aleti-al").setDescription("Aktif kuşatmada anlık Merdiven Grubu veya Koçbaşı alır")
      .addStringOption((o) => o.setName("yerleske").setDescription("Ödemenin yapılacağı saldırgan yerleşkesi").setRequired(true))
      .addStringOption((o) => o.setName("alet").setDescription("Sahada hazırlanacak alet").setRequired(true).addChoices(
        { name: "Merdiven Grubu — 10 Merdiven", value: "ladder_group" },
        { name: "Koçbaşı", value: "ram" }
      ))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Alınacak grup/adet").setMinValue(1).setRequired(true)))
    .addSubcommand((sub) => sub.setName("kusatma-asamasi").setDescription("Kuşatmayı bombardıman veya hücum durumuna geçirir")
      .addStringOption((o) => o.setName("asama").setDescription("Yeni kuşatma durumu").setRequired(true).addChoices(
        { name: "Bombardıman — yalnız Katapultlar sura ateş eder", value: "BOMBARDMENT" },
        { name: "Hücum — ordular temas eder ve savaş zarları açılır", value: "ASSAULT" }
      )))
    .addSubcommand((sub) => sub.setName("bombardiman").setDescription("Katapultlarla bir bombardıman turu oynatır; ordular temas etmez"))
    .addSubcommand((sub) => sub.setName("yayinla").setDescription("Taslağı herkese açık savaş kartı olarak yayımlar"))
    .addSubcommand((sub) => sub.setName("tur-oynat").setDescription("İki açık zar tamamlanınca savaş turunu çözer"))
    .addSubcommand((sub) => sub.setName("ordu-detay").setDescription("Tam birlik kompozisyonunu yalnızca yöneticiye gösterir"))
    .addSubcommand((sub) => sub.setName("kayip-raporu").setDescription("Son savaşın belgeye işlenen ayrıntılı kayıp raporunu yalnızca yöneticiye gösterir"))
    .addSubcommand((sub) => sub.setName("bitir").setDescription("Savaşı yönetici kararıyla sonuçlandırır")
      .addStringOption((o) => o.setName("galip").setDescription("Galip taraf").setRequired(true).addChoices({ name: "A Tarafı", value: "A" }, { name: "B Tarafı", value: "B" }, { name: "Galip Yok", value: "NONE" }))
      .addStringOption((o) => o.setName("neden").setDescription("Herkese açık sonuç açıklaması").setRequired(true).setMaxLength(500)))
    .addSubcommand((sub) => sub.setName("iptal").setDescription("Etkin savaşı iptal eder")),
  new SlashCommandBuilder()
    .setName("npc-devlet-oto-alim").setDescription("Yalnızca yönetici: oyuncusuz devletlerin Alım Turu emirlerini yönetir")
    .addSubcommand((sub) => sub.setName("ayarla").setDescription("NPC otomatik alım sisteminin genel kurallarını ayarlar")
      .addBooleanOption((o) => o.setName("aktif").setDescription("Sistem çalıştırılabilir olsun mu?").setRequired(true))
      .addStringOption((o) => o.setName("doktrin").setDescription("Varsayılan NPC alım doktrini").setRequired(true)
        .addChoices(...Object.entries(NPC_AUTO_PURCHASE_DOCTRINES).map(([value, doctrine]) => ({ name: doctrine.label, value }))))
      .addIntegerOption((o) => o.setName("butce-yuzdesi").setDescription("Toplam yerel hazinenin en fazla harcanacak yüzdesi").setMinValue(1).setMaxValue(100).setRequired(true))
      .addIntegerOption((o) => o.setName("hedef-doluluk").setDescription("Askerî kapasitenin hedeflenen doluluk yüzdesi").setMinValue(1).setMaxValue(100).setRequired(true))
      .addIntegerOption((o) => o.setName("asgari-hazine").setDescription("Ülkede korunacak toplam asgari altın").setMinValue(0).setRequired(true))
      .addStringOption((o) => o.setName("kapsam").setDescription("İşlenecek oyuncusuz ülkeler").setRequired(true).addChoices(
        { name: "Tüm oyuncusuz devletler", value: "ALL_PLAYERLESS" },
        { name: "Yalnızca elle dahil edilenler", value: "INCLUDED_ONLY" }
      )))
    .addSubcommand((sub) => sub.setName("ulke-ayarla").setDescription("Bir ülkeyi kapsama dahil eder, dışlar veya özel doktrin verir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ayarlanacak ülke").setRequired(true))
      .addStringOption((o) => o.setName("durum").setDescription("Ülke kapsam ayarı").setRequired(true).addChoices(
        { name: "Genel ayarı kullan", value: "AUTO" },
        { name: "Kapsama dahil et", value: "INCLUDE" },
        { name: "Kapsam dışında tut", value: "EXCLUDE" }
      ))
      .addStringOption((o) => o.setName("doktrin").setDescription("İsteğe bağlı ülkeye özel doktrin")
        .addChoices(...Object.entries(NPC_AUTO_PURCHASE_DOCTRINES).map(([value, doctrine]) => ({ name: doctrine.label, value })))))
    .addSubcommand((sub) => sub.setName("durum").setDescription("NPC otomatik alım ayarlarını gösterir"))
    .addSubcommand((sub) => sub.setName("onizle").setDescription("Bu Alım Turu için hiçbir ödeme yapmadan emir planını gösterir"))
    .addSubcommand((sub) => sub.setName("calistir").setDescription("Kalan hazine ve kapasiteyle NPC alımlarını uygular; aynı turda tekrar kullanılabilir"))
    .addSubcommand((sub) => sub.setName("ek-alim").setDescription("Aynı Alım Turunda kalan hazine ve kapasiteyle ek NPC alımı yapar")),
  new SlashCommandBuilder()
    .setName("yonetim").setDescription("Oyun yöneticisi komutları")
    .addSubcommand((sub) => sub.setName("ulke-olustur").setDescription("Yeni ülke oluşturur")
      .addStringOption((o) => o.setName("ad").setDescription("Ülke adı").setRequired(true))
      .addIntegerOption((o) => o.setName("hazine").setDescription("Başlangıç hazinesi").setMinValue(0).setRequired(true)))
    .addSubcommand((sub) => sub.setName("ulkeleri-listele").setDescription("Oyundaki bütün aktif devletleri listeler"))
    .addSubcommand((sub) => sub.setName("devlet-belgeleri").setDescription("Bütün devletlerin ayrıntılı bilgi kutularını gösterir"))
    .addSubcommand((sub) => sub.setName("ulke-yok-et").setDescription("Topraksız bir devleti kayıtlarını koruyarak YOK EDİLDİ durumuna alır")
      .addStringOption((o) => o.setName("ulke").setDescription("Yok edilmiş sayılacak ülke").setRequired(true))
      .addStringOption((o) => o.setName("neden").setDescription("Herkese açık/tarihsel yok edilme açıklaması").setRequired(true).setMinLength(2).setMaxLength(500))
      .addStringOption((o) => o.setName("onay").setDescription("Onaylamak için YOK_ET yazın").setRequired(true)))
    .addSubcommand((sub) => sub.setName("yerleske-sil").setDescription("Bir yerleşkeyi ve bağlı bütün verilerini kalıcı olarak siler")
      .addStringOption((o) => o.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Silinecek yerleşke").setRequired(true))
      .addStringOption((o) => o.setName("onay").setDescription("Onaylamak için SIL yazın").setRequired(true)))
    .addSubcommand((sub) => sub.setName("nufus-sil").setDescription("Bir yerleşkeden özgür veya köle nüfus siler")
      .addStringOption((o) => o.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Nüfusun silineceği yerleşke").setRequired(true))
      .addStringOption((o) => o.setName("nufus-turu").setDescription("Silinecek nüfus türü").setRequired(true).addChoices({ name: "Özgür Nüfus", value: "FREE" }, { name: "Köle Nüfusu", value: "SLAVE" }))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Silinecek nüfus miktarı").setMinValue(1).setRequired(true)))
    .addSubcommand((sub) => sub.setName("yerleske-devret").setDescription("Bir yerleşkeyi fethedilmiş olarak başka devlete aktarır")
      .addStringOption((o) => o.setName("kaynak-ulke").setDescription("Yerleşkenin mevcut sahibi").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Aktarılacak yerleşke").setRequired(true))
      .addStringOption((o) => o.setName("hedef-ulke").setDescription("Yerleşkenin yeni sahibi").setRequired(true)))
    .addSubcommand((sub) => sub.setName("oyuncu-ata").setDescription("Oyuncuyu ülkeye atar")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addUserOption((o) => o.setName("oyuncu").setDescription("Oyuncu").setRequired(true)))
    .addSubcommand((sub) => sub.setName("oyuncu-cikar").setDescription("Oyuncunun ülke atamasını kaldırır")
      .addStringOption((o) => o.setName("ulke").setDescription("Oyuncunun çıkarılacağı ülke").setRequired(true))
      .addUserOption((o) => o.setName("oyuncu").setDescription("Ülkeden çıkarılacak oyuncu").setRequired(true)))
    .addSubcommand((sub) => sub.setName("yerleske-ekle").setDescription("Ülkeye yerleşke ekler")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addStringOption((o) => o.setName("ad").setDescription("Yerleşke adı").setRequired(true))
      .addIntegerOption((o) => o.setName("nufus").setDescription("Özgür nüfus").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("kole").setDescription("Köle nüfusu").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("gelir").setDescription("Başlangıç toplam geliri; halk vergisi otomatik ayrılır").setMinValue(0).setRequired(true))
      .addIntegerOption((o) => o.setName("nufus-artisi").setDescription("Alım Turu temel nüfus artışı").setMinValue(0).setRequired(true))
      .addStringOption((o) => o.setName("hammadde").setDescription("Yerleşkenin ürettiği hammadde").setRequired(true).addChoices(...RESOURCE_CHOICES))
      .addStringOption((o) => o.setName("kultur").setDescription("Yerleşkenin kültür grubu; yazmaya başlayarak arayın").setRequired(true).setAutocomplete(true))
      .addBooleanOption((o) => o.setName("kiyi").setDescription("Yerleşke kıyıda mı? Liman inşası için gereklidir")))
    .addSubcommand((sub) => sub.setName("kiyi-ayarla").setDescription("Yerleşkenin kıyı durumunu değiştirir")
      .addStringOption((o) => o.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Yerleşke adı").setRequired(true))
      .addBooleanOption((o) => o.setName("kiyi").setDescription("Kıyı yerleşkesi mi?").setRequired(true)))
    .addSubcommand((sub) => sub.setName("kultur-ayarla").setDescription("Mevcut yerleşkenin kültür grubunu değiştirir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Yerleşke adı").setRequired(true))
      .addStringOption((o) => o.setName("kultur").setDescription("Yeni kültür grubu; yazmaya başlayarak arayın").setRequired(true).setAutocomplete(true)))
    .addSubcommand((sub) => sub.setName("asimilasyon-tamamla").setDescription("Fethedilmiş yerleşkenin asimilasyonunu tamamlar")
      .addStringOption((o) => o.setName("ulke").setDescription("Yerleşkenin bağlı olduğu ülke").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Asimile edilen yerleşke").setRequired(true)))
    .addSubcommand((sub) => sub.setName("hammadde-ayarla").setDescription("Mevcut yerleşkenin hammaddesini değiştirir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Yerleşke adı").setRequired(true))
      .addStringOption((o) => o.setName("hammadde").setDescription("Yeni hammadde").setRequired(true).addChoices(...RESOURCE_CHOICES)))
    .addSubcommand((sub) => sub.setName("tur-ilerlet").setDescription("Yeni turu açar ve bütün otomasyonları işler"))
    .addSubcommand((sub) => sub.setName("tur-durumu").setDescription("Turun hareket durumunu değiştirir")
      .addStringOption((o) => o.setName("durum").setDescription("Yeni durum").setRequired(true)
        .addChoices({ name: "Açık", value: "OPEN" }, { name: "Kapalı", value: "CLOSED" }, { name: "Olaylar çözülüyor", value: "RESOLVING" })))
    .addSubcommand((sub) => sub.setName("yerleske-hazinesi").setDescription("Bir yerleşkenin yerel hazinesini artırır veya azaltır")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Yerleşke adı").setRequired(true))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Negatif değer kullanılabilir").setRequired(true))
      .addStringOption((o) => o.setName("neden").setDescription("İşlem açıklaması").setRequired(true)))
    .addSubcommand((sub) => sub.setName("hazine").setDescription("Ülke hazinesini artırır veya azaltır")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addIntegerOption((o) => o.setName("miktar").setDescription("Negatif değer kullanılabilir").setRequired(true))
      .addStringOption((o) => o.setName("neden").setDescription("İşlem açıklaması").setRequired(true)))
    .addSubcommand((sub) => sub.setName("harap").setDescription("Yerleşkenin harap durumunu değiştirir")
      .addStringOption((o) => o.setName("ulke").setDescription("Ülke adı").setRequired(true))
      .addStringOption((o) => o.setName("yerleske").setDescription("Yerleşke adı").setRequired(true))
      .addBooleanOption((o) => o.setName("harap").setDescription("Harap mı?").setRequired(true)))
    .addSubcommand((sub) => sub.setName("oyunu-sifirla").setDescription("Bu sunucudaki bütün oyun verilerini kalıcı olarak siler")
      .addStringOption((o) => o.setName("onay").setDescription("Onaylamak için büyük harflerle SIFIRLA yazın").setRequired(true)))
    .addSubcommand((sub) => sub.setName("komut-log-kanali").setDescription("Oyuncu bot komutlarının aktarılacağı kanalı ayarlar")
      .addStringOption((o) => o.setName("islem").setDescription("İşlem").setRequired(true).addChoices({ name: "Ayarla", value: "set" }, { name: "Kapat", value: "clear" }))
      .addChannelOption((o) => o.setName("kanal").setDescription("Komut kayıt kanalı").addChannelTypes(ChannelType.GuildText)))
    .addSubcommand((sub) => sub.setName("komut-gecmisi").setDescription("Son oyuncu bot komutlarını gösterir")
      .addIntegerOption((o) => o.setName("adet").setDescription("Gösterilecek kayıt sayısı").setMinValue(1).setMaxValue(25)))
    .addSubcommand((sub) => sub.setName("mesaj-sil").setDescription("Komutun kullanıldığı kanaldaki son mesajları siler")
      .addIntegerOption((o) => o.setName("miktar").setDescription("Silinecek son mesaj sayısı").setMinValue(1).setMaxValue(100).setRequired(true)))
    .addSubcommand((sub) => sub.setName("rol-rapor-kanali").setDescription("Günlük rol sıralamasının gönderileceği kanalı ayarlar")
      .addStringOption((o) => o.setName("islem").setDescription("İşlem").setRequired(true).addChoices({ name: "Ayarla", value: "set" }, { name: "Kapat", value: "clear" }))
      .addChannelOption((o) => o.setName("kanal").setDescription("Günlük rapor kanalı").addChannelTypes(ChannelType.GuildText)))
    .addSubcommand((sub) => sub.setName("rol-kanali").setDescription("Kelime sayılacak rol kanalını ekler veya kaldırır")
      .addStringOption((o) => o.setName("islem").setDescription("İşlem").setRequired(true).addChoices({ name: "Ekle", value: "add" }, { name: "Kaldır", value: "remove" }))
      .addChannelOption((o) => o.setName("kanal").setDescription("Rol kanalı").addChannelTypes(ChannelType.GuildText).setRequired(true)))
].map((builder) => builder.toJSON());

export const buildingChoices = Object.values(BUILDINGS);
export const unitChoices = Object.entries(UNITS).filter(([key]) => !["observer", "militia"].includes(key));
export const shipChoices = Object.entries(SHIPS);
