export const indianCultureGroupsMigration = {
  version: 90,
  name: "indian_culture_groups",
  sql: `
    ALTER TABLE settlements DROP CONSTRAINT IF EXISTS settlements_culture_group_check;
    ALTER TABLE settlements ADD CONSTRAINT settlements_culture_group_check CHECK (culture_group IN (
      'UNASSIGNED','BRITTONIC','CELTIC','GERMANIC','BALTIC','IBERIAN','ITALIC','ILLYRO_PANNONIAN',
      'DACO_GETIC','THRACIAN','HELLENIC','PUNIC','BERBER','LIBYAN','EGYPTIAN','KUSHITIC','HABESHA',
      'ARABIAN','LEVANTINE','MESOPOTAMIAN','ANATOLIAN','ARMENIAN','CAUCASIAN','SARMATIAN','SCYTHIAN',
      'WEST_IRANIAN','EAST_IRANIAN','GANDHARAN','MADHYADESHI','MAGADHAN','KALINGAN','MAHARASHTRI',
      'ANDHRA','TAMIL','SOUTHEAST_ASIAN'
    ));

    ALTER TABLE countries DROP CONSTRAINT IF EXISTS countries_primary_culture_group_check;
    ALTER TABLE countries ADD CONSTRAINT countries_primary_culture_group_check CHECK (primary_culture_group IN (
      'UNASSIGNED','BRITTONIC','CELTIC','GERMANIC','BALTIC','IBERIAN','ITALIC','ILLYRO_PANNONIAN',
      'DACO_GETIC','THRACIAN','HELLENIC','PUNIC','BERBER','LIBYAN','EGYPTIAN','KUSHITIC','HABESHA',
      'ARABIAN','LEVANTINE','MESOPOTAMIAN','ANATOLIAN','ARMENIAN','CAUCASIAN','SARMATIAN','SCYTHIAN',
      'WEST_IRANIAN','EAST_IRANIAN','GANDHARAN','MADHYADESHI','MAGADHAN','KALINGAN','MAHARASHTRI',
      'ANDHRA','TAMIL','SOUTHEAST_ASIAN'
    ));
  `
} as const;
